# Netlify Build Configuration

[build]
  # Build command
  command = "npm run build:seo"
  
  # Directory to publish (default: dist for Vite)
  publish = "dist"
  
  # Functions directory (if you add serverless functions later)
  functions = "netlify/functions"

# Environment variables (set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache favicons
[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200